/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import AnalizadorCSS.IdentificadorCSS;
import AnalizadorGeneral.AnalizarGeneral;
import AnalizadorHTML.IdentificadorHTML;
import AnalizadorHTML.TraductorEtiquetas;
import AnalizadorJS.IdentificadorJS;
import Reportes.Reporte;
import Reportes.ResultadoAnalisis;
import Reportes.Token;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Panel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JEditorPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author alejandro
 */
public class JFrameInicio extends javax.swing.JFrame {
    
    private AnalizarGeneral ag = new AnalizarGeneral();
    private IdentificadorHTML idHTML = new IdentificadorHTML();
    /**
     * Creates new form JFrameInicio
     */
    public JFrameInicio() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButtonCargarArchivo = new javax.swing.JButton();
        jButtonReportes = new javax.swing.JButton();
        jButtonAnalizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAnalizador = new javax.swing.JTextArea();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        jButtonCargarArchivo.setText("Cargar Archivo");

        jButtonReportes.setText("Reportes");
        jButtonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportesActionPerformed(evt);
            }
        });

        jButtonAnalizar.setText("Analizar");
        jButtonAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnalizarActionPerformed(evt);
            }
        });

        jTextAreaAnalizador.setColumns(20);
        jTextAreaAnalizador.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAnalizador);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButtonCargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButtonAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButtonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnalizarActionPerformed
        
        /*
        // Obtener el texto ingresado en el JTextArea
        String texto = jTextAreaAnalizador.getText();

        // Ejecutar el análisis con la clase AnalizarGeneral
        //List<Token> htmlGenerado = ag.analizarTexto(texto);

        // Mostrar el HTML generado en un JEditorPane dentro de un nuevo JFrame
        JFrame ventanaHTML = new JFrame("Resultado del Análisis");
        JEditorPane editorHTML = new JEditorPane("text/html", null);
        editorHTML.setEditable(false);

        JScrollPane scrollPane = new JScrollPane(editorHTML);
        ventanaHTML.getContentPane().add(scrollPane, BorderLayout.CENTER);
        ventanaHTML.setSize(new Dimension(800, 600));
        ventanaHTML.setVisible(true);
        */
        
        // Obtener el texto ingresado en el JTextArea
        String texto = jTextAreaAnalizador.getText();

        // Crear una instancia de la clase AnalizarGeneral
        AnalizarGeneral ag = new AnalizarGeneral();

        // Ejecutar el análisis del texto
        ResultadoAnalisis resultado = ag.analizarTexto(texto);

        // Mostrar los resultados del análisis (tokens encontrados)
        if (!resultado.getTokens().isEmpty()) {
            ag.mostrarResultados(resultado.getTokens());
        } else {
            // Si no se encontraron tokens, mostrar un mensaje
            JFrame ventanaVacia = new JFrame("Sin Resultados");
            JOptionPane.showMessageDialog(ventanaVacia, "No se encontraron tokens en el análisis.", "Resultados", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_jButtonAnalizarActionPerformed

    private void jButtonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportesActionPerformed
     
        // Obtener el texto del área de texto
        String texto = jTextAreaAnalizador.getText().trim(); // .trim() para eliminar espacios en blanco

        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese texto para analizar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear una instancia de IdentificadorHTML o el analizador que necesites
        IdentificadorHTML identificadorHTML = new IdentificadorHTML();
        IdentificadorCSS identificadorCSS = new IdentificadorCSS();
        IdentificadorJS identificadorJS = new IdentificadorJS();
        
        // Analizar el texto y obtener los tokens
        List<Token> tokensHTML = identificadorHTML.obtenerTokensValidos(texto); // Asegúrate de que este método retorne una lista de tokens
        List<Token> tokensCSS = identificadorCSS.obtenerTokensValidos(texto, 1); // Asegúrate de que este método retorne una lista de tokens
        List<Token> tokensJS = identificadorJS.obtenerTokensValidos(texto, 1); // Asegúrate de que este método retorne una lista de tokens

        // Crear una instancia de Reporte y mostrar el reporte
        Reporte reporte = new Reporte();

        reporte.mostrarReporte(tokensHTML, tokensCSS, tokensJS);
        
      
       
    }//GEN-LAST:event_jButtonReportesActionPerformed

    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnalizar;
    private javax.swing.JButton jButtonCargarArchivo;
    private javax.swing.JButton jButtonReportes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaAnalizador;
    // End of variables declaration//GEN-END:variables
}
